linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-blank: true
    check-type-assertions: true
  exhaustive:
    default-signifies-exhaustive: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  godot:
    capital: true
  gofumpt:
    module-path: github.com/jlourenc/xgo
    extra-rules: true
  goheader:
    template: |-
      Copyright {{ YEAR }} Jérémy Lourenço. All rights reserved.
      Use of this source code is governed by a BSD-style
      license that can be found in the LICENSE file.
  goimports:
    local-prefixes: github.com/jlourenc/xgo
  gomnd:
    ignored-numbers:
      - '2'
      - '10'
      - '10.0'
      - '16'
      - '32'
      - '64'
  gomodguard:
    allowed:
      modules: []
      domains: []
  gosimple:
    checks: ['all']
    settings:
      shadow:
        strict: true
  gosmopolitan:
    allow-time-local: true
  govet:
    check-shadowing: true
    enable-all: true
  misspell:
    locale: US
  nolintlint:
    require-explanation: true
    require-specific: true
  prealloc:
    for-loops: true
  revive:
    enable-all-rules: true
    rules:
      - name: add-constant
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: deep-exit
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: function-length
        arguments: [50,100]
      - name: line-length-limit
        arguments: [150]
      - name: unhandled-error
        arguments:
          - 'fmt\.F?(P|p)rint(f|ln)?'
          - 'strings\.Builder\.WriteString'
  staticcheck:
    checks: ['all']
  stylecheck:
    checks: ['all']
    http-status-code-whitelist: []
  tenv:
    all: true
  usestdlibvars:
    constant-kind: true
    crypto-hash: true
    default-rpc-path: true
    os-dev-null: true
    sql-isolation-level: true
    time-layout: true
    time-month: true
    tls-signature-scheme: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - dogsled
    - dupl
    - durationcheck
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - inamedparam
    - interfacebloat
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - dupl
        - errcheck
        - goconst
        - gomnd
        - govet
        - lll
    - path: _test\.go
      text: "function-length"
      linters:
        - revive
