linters-settings:
  depguard:
    list-type: allowlist
    include-go-root: false
  dupl:
    threshold: 100
  errcheck:
    check-blank: true
    check-type-assertions: true
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 25
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/jlourenc/xgo
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  gomodguard:
    allowed:
      modules: []
      domains: []
  gosimple:
    go: 1.18
    checks: [all]
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  misspell:
    locale: US
  nestif:
    min-complexity: 6
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  staticcheck:
    go: 1.18
    checks: [all]
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - deadcode
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - exhaustive
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - lll
    - maintidx
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - funlen
        - goconst
        - gomnd
        - ifshort
        - lll
