linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-blank: true
    check-type-assertions: true
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  godot:
    capital: true
  goheader:
    template: |-
      Copyright {{ YEAR }} Jérémy Lourenço. All rights reserved.
      Use of this source code is governed by a BSD-style
      license that can be found in the LICENSE file.
  goimports:
    local-prefixes: github.com/jlourenc/xgo
  gomnd:
    ignored-numbers:
      - '2'
      - '10'
      - '10.0'
      - '16'
      - '32'
      - '64'
  gomodguard:
    allowed:
      modules: []
      domains: []
  gosimple:
    checks: [all]
    settings:
      shadow:
        strict: true
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    require-explanation: true
    require-specific: true
  prealloc:
    for-loops: true
  staticcheck:
    checks: [all]
  stylecheck:
    checks: [all]
    http-status-code-whitelist: []
  tenv:
    all: true
  usestdlibvars:
    constant-kind: true
    crypto-hash: true
    default-rpc-path: true
    os-dev-null: true
    sql-isolation-level: true
    time-layout: true
    time-month: true
    tls-signature-scheme: true
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - maintidx
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - funlen
        - goconst
        - gomnd
        - lll
