ci: true
plugins:
  - "@semantic-release/commit-analyzer@v9"
  - "@semantic-release/release-notes-generator@v10"
  - "@semantic-release/github@v8"
  - "conventional-changelog-conventionalcommits@v4"
preset: conventionalcommits
