ci: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - "conventional-changelog-conventionalcommits@v4"
preset: conventionalcommits
