---
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  # coverage
  cover:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
  # linters
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45
  # tests
  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        golang: [1.16, 1.17, 1.18]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      XGO_XERRORS_ENABLE_STACK_TRACE: true
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.golang }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: go test -v --race -coverprofile=covprofile ./...
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: covprofile
          flag-name: ${{ runner.os }}-go-${{ matrix.golang }}
          parallel: true
