---
name: PR
on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - edited
      - synchronize
jobs:
  # semantic versioning
  semver:
    runs-on: ubuntu-latest
    steps:
      - name: Semantic release
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
